version: '3.8'

services:
  weather-backend:
    build: .
    ports:
      - "8080:8080"
    environment:
      - FLASK_ENV=development
      - GCS_BUCKET_NAME=${GCS_BUCKET_NAME:-weather-data-bucket}
      - GOOGLE_CLOUD_PROJECT=${GOOGLE_CLOUD_PROJECT}
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
    volumes:
      - ${GOOGLE_APPLICATION_CREDENTIALS}:/app/credentials.json:ro
    env_file:
      - .env
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
